# docker compose build
# docker compose run --rm state_estimation bash

services:
  state_estimation:
    build:
      context: docker
      dockerfile: Dockerfile_ros2
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    image: path_planning-image
    container_name: state_estimation-container
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/home/ubuntu/.Xauthority
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${HOME}/.Xauthority:/home/ubuntu/.Xauthority:ro"
      - ${PWD}/state_estimation:/home/ubuntu/state_estimation:rw
    network_mode: host
    tty: true
    stdin_open: true
    working_dir: /home/ubuntu/state_estimation
    command: /bin/bash
    restart: unless-stopped
