FROM osrf/ros:jazzy-desktop-full

ARG DEBIAN_FRONTEND=noninteractive


########################
# INSTALL DEPENDENCIES #
########################

# Update
RUN apt update && apt upgrade -y

RUN apt install --quiet -y \
    sudo software-properties-common lsb-release
RUN add-apt-repository universe

# Ubuntu deps
RUN apt install --quiet -y \
    apt-transport-https ca-certificates gnupg gnupg2 gnupg-agent libssl-dev \
    git curl file wget zip unzip pkg-config openssh-client openssh-server \
    xterm tmux gdb valgrind \
    htop net-tools nmap lynx \
    libx11-dev vim iputils-ping

RUN apt install --quiet -y \
    bash-completion
RUN echo "source /usr/share/bash-completion/completions/git" >> ~/.bashrc

# C++ deps
RUN apt install --quiet -y \
    build-essential clang cmake ccache ninja-build

# C++ linter
RUN apt install --quiet -y \
    clang-tidy clang-tools \
    cppcheck \
    astyle

# C++ testing deps
RUN apt install --quiet -y libgtest-dev libgmock-dev lcov

# C++ Boost lib
RUN apt install --quiet -y \
    libboost-all-dev

# C++ Eigen lib
RUN apt install --quiet -y \
    libeigen3-dev


# Python deps
RUN apt install --quiet -y \
    python3 python3-dev python3-pip python3-future

# Python linter
RUN apt install --quiet -y pylint

# Python test libs
RUN apt install --quiet -y python3-pytest


# Plotjuggler
RUN apt install -y --quiet ros-${ROS_DISTRO}-plotjuggler-ros


# Clean
USER root
RUN apt -y autoremove && apt clean autoclean \
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# Set user
USER ubuntu
WORKDIR /home/ubuntu

# Set entrypoint
COPY entrypoint_ros2.sh /
ENTRYPOINT ["/entrypoint_ros2.sh"]

ENV force_color_prompt=yes
CMD ["bash"]
